### ISSUE TITLE
package должен называться domain

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/Searcher-HouseService#1]
https://github.com/NailMukhametshin/Searcher-HouseService/blob/9527fc80b678d37c661075a0368c3df3dce8a719/src/ru/itpark/domin/House.java#L1

**Comment by NailMukhametshin** [comment]
@coursar, исправил в b2b5020c97d2c492a1fad88638131d5dd060cb7d https://github.com/NailMukhametshin/Searcher-HouseService/blob/b2b5020c97d2c492a1fad88638131d5dd060cb7d/src/ru/itpark/domain/House.java#L1
