### ISSUE TITLE
Разве PriceComparator должен сравнивать не дома?

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/Searcher-HouseService#2]
https://github.com/NailMukhametshin/Searcher-HouseService/blob/9527fc80b678d37c661075a0368c3df3dce8a719/src/ru/itpark/comparator/PriceComparator.java#L5-L11

Должно быть:
```java
implements Comparator<House>
```

**Comment by NailMukhametshin** [comment]
@coursar, исправил в 98c1ad474cd2df9806e74a0fc97dbd1d57e4b353 https://github.com/NailMukhametshin/Searcher-HouseService/blob/98c1ad474cd2df9806e74a0fc97dbd1d57e4b353/src/ru/itpark/comparator/PriceComparator.java#L7-L13
