### ISSUE TITLE
Используйте List для districts и метод contains вместо цикла

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/Searcher-HouseService#3]
https://github.com/NailMukhametshin/Searcher-HouseService/blob/9527fc80b678d37c661075a0368c3df3dce8a719/src/ru/itpark/service/HouseService.java#L24-L37

**Comment by NailMukhametshin** [comment]
@coursar, исправил в dda3fc5cdc0225b2a9da6b61a6f127cbceab0d49 https://github.com/NailMukhametshin/Searcher-HouseService/blob/dda3fc5cdc0225b2a9da6b61a6f127cbceab0d49/src/ru/itpark/service/HouseService.java#L25-L37

**Comment by coursar** [comment]
Закрывайте Issue, если сделали. Лучше это сразу делать сообщением в коммите: 'fixed #3'
