### ISSUE TITLE
Сортировать нужно в сервисе

### ISSUE THREAD

**Issue by coursar** [NailMukhametshin/Searcher-HouseService#4]
https://github.com/NailMukhametshin/Searcher-HouseService/blob/9527fc80b678d37c661075a0368c3df3dce8a719/src/ru/itpark/Main.java#L26

Допускается, конечно, и так. Но в данной задаче это нужно делать в сервисе.

**Comment by NailMukhametshin** [comment]
@coursar, исправил в a9fd9a1f7746078afa462db8c1c4647b060d28ed
